name: ab_testing_example
description: An example Flutter project for the ab_testing package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  ab_testing_core: ^1.0.1
  ab_testing_firebase: ^1.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.0
  firebase_remote_config: ^6.1.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
