name: ab_testing
repository: https://github.com/programmierbar/ab_testing

packages:
  - core
  - firebase
  - example

scripts:
  format: dart format .

  format:check: dart format --set-exit-if-changed .

  analyze: dart analyze --fatal-infos .
